name: Deploy and Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Staging Deployment
        run: echo "Staging environment deployed "

  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm i
          npm i cypress

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress Tests
        env:
          CYPRESS_EMAIL: ${{ secrets.EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_TOTPSECRET: ${{ secrets.TOTP_SECRET }}
        run: |
          echo "Running Cypress with email=$CYPRESS_EMAIL"
          npx cypress run \
            --env email=$CYPRESS_EMAIL,password=$CYPRESS_PASSWORD,totpSecret=$CYPRESS_TOTPSECRET

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: cypress-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Dev Deployment
        run: echo "Dev environment deployed"
